### ISSUE TITLE
你好 我想问下签名的问题 总是报签名错误

### ISSUE THREAD

**Issue by renyufei8023** [hellophil/phil_wechat#1]

**Comment by philjing** [comment]
是你写的问题吧，可以把代码发到我邮箱吗？

**Comment by renyufei8023** [comment]
签名已经没有问题了 我手动获取的code，然后再使用code去获取openid，之前是因为openid有问题。
我想问一下就是如果在页面上进行获取code以及openid应该怎么做呢

**Comment by philjing** [comment]
页面获取code和openid? 为什么不在controller里面获取然后返回结果到页面，我的代码已经很完整了，请您仔细阅读

**Comment by renyufei8023** [comment]
嗯嗯 我知道怎么弄了  那个回调地址的时候去请求controller里面的方法然后获取code 然后再获取openid。 谢谢了，
